#
ccflags-y += -I$(srctree)/drivers/misc/mediatek/performance/resym
ccflags-y += -Idrivers/misc/mediatek/vpu/mt6768/
ccflags-y += -Idrivers/misc/mediatek/mdla/1.0/

obj-y += rs_vpu_pfm.o
obj-y += rs_mdla_pfm.o

