obj-y += adsp_helper.o
obj-y += adsp_load.o
obj-y += adsp_ipi_queue.o

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(CONFIG_MTK_PLATFORM)/include/mach
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hifi_dsp/$(CONFIG_MTK_PLATFORM)
