#
ccflags-$(CONFIG_ZRAM) += -I$(srctree)/drivers/block/zram
ccflags-$(CONFIG_ZSMALLOC) += -I$(srctree)/drivers/staging/zsmalloc
ccflags-y += -I$(srctree)/drivers/staging/android/ion

obj-y += mlog_logger.o
