#
ccflags-y += \
	-I$(srctree)/kernel/trace/ \

ccflags-$(CONFIG_MTK_FPSGO) += \
	-I$(srctree)/drivers/misc/mediatek/performance/fpsgo/fstb/ \

ccflags-$(CONFIG_MTK_FPSGO_V3) += \
	-I$(srctree)/drivers/misc/mediatek/performance/fpsgo_v3/fstb/ \

obj-y += utch.o
