#
obj-y += fstb.o

MTK_TOP = $(srctree)/drivers/misc/mediatek/

ccflags-y  += -I$(srctree)/drivers/misc/mediatek/video/include
ccflags-y  += -I$(srctree)/drivers/misc/mediatek/gpu/ged/include
ccflags-y  += -I$(srctree)/drivers/misc/mediatek/dfrc/
ccflags-y  += -I$(srctree)/kernel/trace/
ccflags-y  += -I$(MTK_TOP)/base/power/include/
ccflags-y  += -I$(MTK_TOP)/base/power/$(MTK_PLATFORM)/
ccflags-y  += -I$(MTK_TOP)/performance/fpsgo_v3/base/include
ccflags-y  += -I$(MTK_TOP)/performance/fpsgo_v3/eara_job/include
ccflags-y  += -I$(MTK_TOP)/performance/include
