#
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/$(CONFIG_MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/audio_ipi/common/framework
ccflags-y += -I$(srctree)/drivers/misc/mediatek/vow
ccflags-y += -I$(srctree)/drivers/misc/mediatek/vow/$(CONFIG_MTK_PLATFORM)

obj-y += vow.o