#
MTK_GPU_VERSION = $(subst ",,$(CONFIG_MTK_GPU_VERSION))
$(info *MTK_GPU_VERSION = $(MTK_GPU_VERSION))

ifeq ($(word 2,$(MTK_GPU_VERSION)),clark)
	obj-y += m1.13ED5776728/
else ifeq ($(word 2,$(MTK_GPU_VERSION)),auckland)
	obj-y += m1.13ED5776728/
endif
