#
MTK_TOP = $(srctree)/drivers/misc/mediatek/
ccflags-y  += -I$(MTK_TOP)/performance/fpsgo_v3/base/include/
ccflags-y  += -I$(MTK_TOP)/performance/fpsgo_v3/fstb/

obj-y += gbe1_main.o
obj-y += gbe2_main.o
obj-y += gbe_common.o
obj-y += gbe_sysfs.o
