#
obj-y += memory-amms.o
MTK_TOP = $(srctree)/drivers/misc/mediatek/
ccflags-y += -I$(srctree)/drivers/devfreq/
ccflags-y += -I$(MTK_TOP)/base/power/include/
ccflags-y += -I$(MTK_TOP)/base/power/$(MTK_PLATFORM)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat

