#
subdir-ccflags-y += -Werror -I$(srctree)/drivers/usb/mtu3
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/

obj-y += mtu3_hal.o mtu3_phy_hal.o mtu3_sleep.o mtu3_phy_debugfs.o
