#
ccflags-y += -I$(srctree)/drivers/misc/mediatek/performance/resym
ccflags-y += -I$(srctree)/drivers/misc/mediatek/apusys/power/2.0/$(MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/apusys/power/2.0

obj-y += rs_vpu_pfm.o
obj-y += rs_mdla_pfm.o

