#
MTK_TOP = $(srctree)/drivers/misc/mediatek/
ccflags-y += \
	-I$(MTK_TOP)/base/power/include/ \
	-I$(MTK_TOP)/base/power/$(MTK_PLATFORM)/ \
	-I$(MTK_TOP)/dramc/$(MTK_PLATFORM)/ \
	-I$(srctree)/drivers/misc/mediatek/performance/boost_ctrl/include/ \

obj-y += eas_ctrl.o

